### ISSUE TITLE
Award shipping

### ISSUE THREAD

**Issue by weaverbel** [carpentries/community-service-awards#1]
Hi @rgaiacs I think the award would have to be shipped from the US as I don't have the award. Do you want me to take that up with Tracy? Otherwise I am OK with my tasks on this.

**Comment by tracykteal** [comment]
Yes, we can do the awards shipping from the US.

**Comment by rgaiacs** [comment]
> > I think the award would have to be shipped from the US
>
> we can do the awards shipping from the US.

No problem.

> Otherwise I am OK with my tasks on this.

Thanks.
